default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Event_planning_API_development
  username: Event_planning_API
  password: "Event_planning_API"

test:
  <<: *default
  database: Event_planning_API_test

production:
  <<: *default
  database: Event_planning_API_production
  username: Event_planning_API
  password: <%= ENV['EVENT_PLANNING_API_DATABASE_PASSWORD'] %>
