# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d4505038a13a0e54cae5e0f89f934d977cb4b625349d117b73aa903e16bcfaa6a8f36c0ba611e32a56011cbb7ed875efdcfe5e5fea1c3b20c24fedc4653f297

test:
  secret_key_base: 7d85ead7fd649cb8ee3f66b4c8dea6e788103ba83d92ffb2d643b2d8b1cf53ba9a560ecba9a635497b1c274266ce192259becbf64a6199fc24a4a7e34eb111e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
